Added composite name variable set

diff --git a/.github/workflows/Test_installation_assistant.yml b/.github/workflows/Test_installation_assistant.yml
--- a/.github/workflows/Test_installation_assistant.yml
+++ b/.github/workflows/Test_installation_assistant.yml
@@ -65,3 +65,42 @@ jobs:
 
     - name: View parameters
       run: echo "${{ toJson(inputs) }}"
+    
+    - name: Set COMPOSITE_NAME variable
+      run: |
+        case "${{ inputs.SYSTEM }}" in
+          "CentOS 7")
+            SUBNAME="centos-7"
+            ;;
+          "CentOS 8")
+            SUBNAME="centos-8"
+            ;;
+          "Amazon Linux 2")
+            SUBNAME="amazon-2"
+            ;;
+          "Ubuntu 16")
+            SUBNAME="ubuntu-16.04"
+            ;;
+          "Ubuntu 18")
+            SUBNAME="ubuntu-18.04"
+            ;;
+          "Ubuntu 20")
+            SUBNAME="ubuntu-20.04"
+            ;;
+          "Ubuntu 22")
+            SUBNAME="ubuntu-22.04"
+            ;;
+          "RHEL7")
+            SUBNAME="redhat-7"
+            ;;
+          "RHEL8")
+            SUBNAME="redhat-8"
+            ;;
+          *)
+            echo "Invalid SYSTEM selection" >&2
+            exit 1
+            ;;
+        esac
+        COMPOSITE_NAME="${COMPOSITE_NAME/SUBNAME/$SUBNAME}"
+        echo "COMPOSITE_NAME=$COMPOSITE_NAME" >> $GITHUB_ENV
+        
